version: "3.4"


services:
    flinbusmerge:
        build: .
        network_mode: host
        environment:
          - POSTGRES_HOST=localhost
          - POSTGRES_USER=flinbus
          - POSTGRES_DB=flinbus
          - POSTGRES_PASSWORD=31432014320143012343124654107
          - FLINBUSMERGE_HOST_ADDRESS=0.0.0.0:8080
          - FLINBUSML_URL=http://localhost:8081
          #- FLINBUSML_URL=http://93.140.127.33:8080
